name: Sync up to AWS CodeCommit Action
description: 'Sync to aws'
author: 'nsan'
branding:
  icon: terminal
  color: yellow
inputs:
  repository_name:
    description: CodeCommit repository name.
    required: true
  aws_region:
    description: Region of the CodeCommit repository.
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
